# Generated by Django 3.0.5 on 2020-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapCity',
            fields=[
                ('title_head', models.CharField(max_length=20000, verbose_name='标志')),
                ('name', models.CharField(max_length=20, verbose_name='类型')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'MapCity',
            },
        ),
    ]
